# Generated by Django 5.2.7 on 2025-11-02 12:48

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa roli')),
                ('symbol', models.CharField(choices=[('user', 'User'), ('moderator', 'Moderator'), ('admin', 'Admin')], max_length=20, unique=True, verbose_name='Symbol')),
            ],
            options={
                'verbose_name': 'Rola',
                'verbose_name_plural': 'Role',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('email_verified', models.BooleanField(default=False, verbose_name='Email zweryfikowany')),
                ('google_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Google ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='uploader.role', verbose_name='Rola')),
            ],
            options={
                'verbose_name': 'Użytkownik',
                'verbose_name_plural': 'Użytkownicy',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Tytuł')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('video_file', models.FileField(upload_to='videos/%Y/%m/%d/', verbose_name='Plik wideo')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='Czas trwania (sekundy)')),
                ('resolution', models.CharField(blank=True, max_length=20, verbose_name='Rozdzielczość')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='Rozmiar pliku (bajty)')),
                ('status', models.CharField(choices=[('uploaded', 'Wgrane'), ('processing', 'Przetwarzanie'), ('completed', 'Gotowe'), ('failed', 'Błąd')], default='uploaded', max_length=20, verbose_name='Status')),
                ('target_duration', models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(180)], verbose_name='Docelowa długość shorta (sekundy)')),
                ('max_shorts_count', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Maksymalna liczba shortów')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Wideo',
                'verbose_name_plural': 'Wideo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Short',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Tytuł')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('short_file', models.FileField(upload_to='shorts/%Y/%m/%d/', verbose_name='Plik shorta')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/%Y/%m/%d/', verbose_name='Miniaturka')),
                ('start_time', models.FloatField(verbose_name='Czas rozpoczęcia w źródłowym wideo (sekundy)')),
                ('duration', models.IntegerField(verbose_name='Czas trwania (sekundy)')),
                ('order', models.IntegerField(default=0, verbose_name='Kolejność')),
                ('upload_status', models.CharField(choices=[('pending', 'Oczekuje'), ('uploading', 'Uploadowanie'), ('published', 'Opublikowany'), ('failed', 'Błąd'), ('scheduled', 'Zaplanowany')], default='pending', max_length=20, verbose_name='Status uploadu')),
                ('yt_video_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID wideo na YouTube')),
                ('yt_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Link YouTube')),
                ('privacy_status', models.CharField(choices=[('public', 'Publiczny'), ('unlisted', 'Niepubliczny'), ('private', 'Prywatny')], default='public', max_length=20, verbose_name='Widoczność')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Zaplanowana publikacja')),
                ('made_for_kids', models.BooleanField(default=False, verbose_name='Dla dzieci')),
                ('views', models.IntegerField(default=0, verbose_name='Wyświetlenia')),
                ('likes', models.IntegerField(default=0, verbose_name='Polubienia')),
                ('comments', models.IntegerField(default=0, verbose_name='Komentarze')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Data publikacji')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shorts', to='uploader.video', verbose_name='Źródłowe wideo')),
            ],
            options={
                'verbose_name': 'Short',
                'verbose_name_plural': 'Shorty',
                'ordering': ['video', 'order'],
            },
        ),
        migrations.CreateModel(
            name='YTAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=100, verbose_name='Nazwa kanału')),
                ('channel_id', models.CharField(max_length=100, unique=True, verbose_name='ID kanału')),
                ('access_token', models.CharField(max_length=255, verbose_name='Access Token')),
                ('refresh_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Refresh Token')),
                ('token_expiry', models.DateTimeField(blank=True, null=True, verbose_name='Wygaśnięcie tokena')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data połączenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yt_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Konto YouTube',
                'verbose_name_plural': 'Konta YouTube',
                'ordering': ['-created_at'],
            },
        ),
    ]
