# Generated by Django 5.2.7 on 2025-11-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='processing_message',
            field=models.CharField(blank=True, max_length=255, verbose_name='Wiadomość statusu'),
        ),
        migrations.AddField(
            model_name='video',
            name='processing_progress',
            field=models.IntegerField(default=0, verbose_name='Postęp przetwarzania (%)'),
        ),
        migrations.AddField(
            model_name='video',
            name='shorts_created',
            field=models.IntegerField(default=0, verbose_name='Liczba utworzonych shortów'),
        ),
        migrations.AddField(
            model_name='video',
            name='shorts_total',
            field=models.IntegerField(default=0, verbose_name='Całkowita liczba shortów do utworzenia'),
        ),
    ]
