# Generated by Django 5.2.7 on 2025-11-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_video_processing_message_video_processing_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(choices=[('local', 'Email/Password'), ('google', 'Google OAuth')], default='local', max_length=20, verbose_name='Metoda logowania'),
        ),
        migrations.AddField(
            model_name='user',
            name='google_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Google Email'),
        ),
        migrations.AddField(
            model_name='user',
            name='google_picture',
            field=models.URLField(blank=True, null=True, verbose_name='Google Avatar URL'),
        ),
        migrations.AddField(
            model_name='ytaccount',
            name='client_id',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Client ID (z user credentials)'),
        ),
        migrations.AddField(
            model_name='ytaccount',
            name='client_secret',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Client Secret (z user credentials)'),
        ),
        migrations.AddField(
            model_name='ytaccount',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktywne połączenie'),
        ),
        migrations.AddField(
            model_name='ytaccount',
            name='last_sync',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ostatnia synchronizacja'),
        ),
        migrations.AlterField(
            model_name='ytaccount',
            name='access_token',
            field=models.TextField(verbose_name='Access Token'),
        ),
        migrations.AlterField(
            model_name='ytaccount',
            name='channel_id',
            field=models.CharField(max_length=100, verbose_name='ID kanału'),
        ),
        migrations.AlterField(
            model_name='ytaccount',
            name='refresh_token',
            field=models.TextField(blank=True, null=True, verbose_name='Refresh Token'),
        ),
    ]
