# Generated by Django 5.2.7 on 2025-11-20 17:45

from django.db import migrations


def remove_allauth_tables(apps, schema_editor):
    """Remove django-allauth tables from database"""
    with schema_editor.connection.cursor() as cursor:
        # Drop allauth tables
        tables_to_drop = [
            'account_emailaddress',
            'account_emailconfirmation',
            'socialaccount_socialaccount',
            'socialaccount_socialapp',
            'socialaccount_socialapp_sites',
            'socialaccount_socialtoken',
            'django_site',  # Also remove django.contrib.sites
        ]
        
        for table in tables_to_drop:
            try:
                cursor.execute(f"DROP TABLE IF EXISTS {table};")
            except Exception as e:
                print(f"Could not drop table {table}: {e}")


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_user_auth_provider_user_google_email_and_more'),
    ]

    operations = [
        migrations.RunPython(remove_allauth_tables, migrations.RunPython.noop),
    ]
