# Generated by Django 4.2.26 on 2025-11-23 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0004_remove_allauth_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='short',
            name='average_view_duration',
            field=models.FloatField(default=0, verbose_name='Średni czas oglądania (sekundy)'),
        ),
        migrations.AddField(
            model_name='short',
            name='click_through_rate',
            field=models.FloatField(default=0, verbose_name='CTR (%)'),
        ),
        migrations.AddField(
            model_name='short',
            name='description_length',
            field=models.IntegerField(default=0, verbose_name='Długość opisu'),
        ),
        migrations.AddField(
            model_name='short',
            name='engagement_rate',
            field=models.FloatField(default=0, verbose_name='Wskaźnik zaangażowania (%)'),
        ),
        migrations.AddField(
            model_name='short',
            name='hashtags_count',
            field=models.IntegerField(default=0, verbose_name='Liczba hashtagów'),
        ),
        migrations.AddField(
            model_name='short',
            name='last_analytics_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ostatnia aktualizacja analityki'),
        ),
        migrations.AddField(
            model_name='short',
            name='retention_rate',
            field=models.FloatField(default=0, verbose_name='Retencja (%)'),
        ),
        migrations.AddField(
            model_name='short',
            name='shares',
            field=models.IntegerField(default=0, verbose_name='Udostępnienia'),
        ),
        migrations.AddField(
            model_name='short',
            name='title_length',
            field=models.IntegerField(default=0, verbose_name='Długość tytułu'),
        ),
        migrations.AddField(
            model_name='short',
            name='watch_time_minutes',
            field=models.FloatField(default=0, verbose_name='Czas oglądania (minuty)'),
        ),
        migrations.CreateModel(
            name='ShortSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('title', 'Tytuł'), ('description', 'Opis'), ('thumbnail', 'Miniatura'), ('timing', 'Czas publikacji'), ('content', 'Treść wideo'), ('engagement', 'Zaangażowanie')], max_length=20, verbose_name='Kategoria')),
                ('priority', models.CharField(choices=[('low', 'Niska'), ('medium', 'Średnia'), ('high', 'Wysoka'), ('critical', 'Krytyczna')], default='medium', max_length=10, verbose_name='Priorytet')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł sugestii')),
                ('description', models.TextField(verbose_name='Opis sugestii')),
                ('metric_name', models.CharField(blank=True, max_length=50, verbose_name='Nazwa metryki')),
                ('current_value', models.FloatField(blank=True, null=True, verbose_name='Aktualna wartość')),
                ('target_value', models.FloatField(blank=True, null=True, verbose_name='Wartość docelowa')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Rozwiązane')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('short', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='uploader.short', verbose_name='Short')),
            ],
            options={
                'verbose_name': 'Sugestia',
                'verbose_name_plural': 'Sugestie',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
