# Generated by Django 4.2.26 on 2025-11-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0005_short_average_view_duration_short_click_through_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='short',
            name='tags',
            field=models.CharField(blank=True, help_text='Tagi oddzielone przecinkami', max_length=500, verbose_name='Tagi'),
        ),
        migrations.AddField(
            model_name='short',
            name='tags_count',
            field=models.IntegerField(default=0, verbose_name='Liczba tagów'),
        ),
        migrations.AlterField(
            model_name='short',
            name='hashtags_count',
            field=models.IntegerField(default=0, verbose_name='Liczba hashtagów w opisie'),
        ),
    ]
